### PR TITLE
Add support for bundling only themes defined by glob pattern

### PR DESCRIPTION
**Pull request by Igloczek**

### CODE REVIEW

**Comment by krzksz** [comment]
LGTM, thanks for contributing! Could you please adjust the usage documentation in README.md?

**Comment by Igloczek** [comment]
Some short description added.

**Comment by kantakt2** [comment]
This not working.
because must be in line 43 => `.action(({ config, debug, glob }) => {` now there is `.action(({ config, debug }) => {` in **cli.js**



and also on line 48 must be `require('./lib/bundle')(config, glob).catch(logger.error);` now there is just `require('./lib/bundle')(config).catch(logger.error);`

**Comment by Igloczek** [comment]
@kantakt2 Thanks for sporting this, you are right, I'll prepare w fix for that!

**Pull request merged**
